### ISSUE TITLE
Add ability to reload saved reports from drag/drop box

### ISSUE THREAD

**Issue by mattgarrish** [daisy/ace-smart#1]
Currently, the only way to reload is from the history table, but if the database identifier is added to the saved evaluation json, it should be possible to automatically determine which evaluation the data belongs to.

/cc @clapierre

**Comment by clapierre** [comment]
I see, thats interesting.  Will downloaded SMART JSON files automatically get saved as well?
Just wondering if you download but don't save the evaluation on your server then that would break unless they are autosaved.
Thanks
Charles.
________________________________

**Comment by mattgarrish** [comment]
No, you don't need to save the evaluation to the smart server to get an identifier. The identifier is assigned as soon as you load the ace report (or create a blank evaluation) as I have to log the evaluation in the database no matter how you subsequently choose to save it.

When you drop the saved evaluation on the upload area (in the future), the script on the server will be able to read the assigned ID from the json and then tie the evaluation back to its db record.

Without the identifier, I don't know where that saved data came from so if you decide to save to the server the next time, I can't attach it back to the right evaluation in the database.

**Comment by mattgarrish** [comment]
Forgot to update this issue, but I've deployed code that now allows reloading through the drag/drop box. It'll only work for evaluations saved from Feb. 1 on, though. If you try to load an evaluation before the code was implemented, you'll just get a message that it has can only be loaded through the evaluation history.
