### ISSUE TITLE
Order of WCAG-criteria incorrect

### ISSUE THREAD

**Issue by riekevullings** [daisy/ace-smart#2]
There seems to be a mix-up of WCAG-criteria in the Conformance part of SMART. The current order under the Conformance tab is:

- 3.3.7 Accessible Authentication Level AA
- 3.3.8 Accessible Authentication (No Exception) Level AAA
- 3.3.9 Redundant Entry Level A

In [WCAG 2.2](https://www.w3.org/TR/WCAG22/#redundant-entry) the order is:

- Success Criterion 3.3.7 Redundant Entry (A)
- Success Criterion 3.3.8 Accessible Authentication (Minimum) (AA)
- Success Criterion 3.3.9 Accessible Authentication (Enhanced) (AAA)

The same happens in the report.

**Comment by mattgarrish** [comment]
Thanks, yes, WCAG 2.2 support was initially added as a preview after the first [CR snapshot](https://www.w3.org/TR/2022/CR-WCAG22-20220906/) was released. In that draft, the order was the same as on the site. I'll get the site updated shortly.

**Comment by mattgarrish** [comment]
The order is now fixed on the site. Note that I can't tweak individual reports, so if you set different statuses for 3.3.7-3.3.9 they'll need to be manually readjusted to match the reordered success criteria.

Thanks again for the report!

**Comment by riekevullings** [comment]
Thank you!
