### ISSUE TITLE
Feedback - Monthly Evaluation Limit too Low

### ISSUE THREAD

**Issue by lb803** [daisy/ace-smart#2]
Hello!
I really like `ace-smart`, and I would like to use it more!

The non-profit publishing house I work for has an output of 2-4 books per month, which clashes with the current `ace-smart` evaluation limit of 2 reports per month.

I was wondering if the 2 reports/mo limitation is part of a development phase and if you are planning to re-consider this in the future?

Thanks for your dev efforts!

**Comment by lb803** [comment]
Fantastic, thanks!

**Comment by mattgarrish** [comment]
FYI, smart is now available to everyone with unlimited access. You don't have to do anything if you've already got an account; they've all been migrated.

**Comment by lb803** [comment]
This is great to know, thanks for dropping a message!
