### ISSUE TITLE
typo in pop up window message

### ISSUE THREAD

**Issue by bernie038** [daisy/ace-smart#5]
This is a VERY MINOR thing: When I processed the ACE report in the ACE Smart Evaluation online it gave me this message in a pop up window:

The following accessibiity features were found in the metadata but do not match known values:
	ttsMarkup

"accessibiity" is spelled incorrectly in this pop up window message (just letting know.) 

All the important features are working perfectly for our titles!

Thank you.

**Comment by mattgarrish** [comment]
All reports are helpful! In this case, I caught two other instances of that typo that got copied and pasted into other messages.

It was also strange that you were getting a message that ttsMarkup is unknown as it's definitely in the metadata. I've fixed the bug in the code that was causing that message to display, but in the metadata tab you'll have to manually re-check the "text-to-speech markup" feature for the report you already imported.

Thanks again for the report!
